Write a Python program to check whether a student has failed or not: The input data is students' semester marks, which is supplied as an external file.


In [7]:
import numpy as np
import pandas as pd

In [8]:
data=pd.read_csv('Student_data.csv')
marks=data[['c1','c2','c3','c4','c5','c6']].values
for X in marks:
    flag=0
    for i in X:
        if i<50:
            flag=1
            break
    print(X,end=' --> ')
    if(flag):
        print('Fail')
    else:
        print('Pass')
            



[58 17 74 58 11 63] --> Fail
[56 74 99 26 10  3] --> Fail
[41 16 32 26 94 47] --> Fail
[62 32 70 25 49 37] --> Fail
[60 76 20  4 41 58] --> Fail
[42 66 15 84 38 15] --> Fail
[64 79 58 68 65 66] --> Pass
[43 93 82 92 15 73] --> Fail
[56 57 10 21 94 27] --> Fail
[95 87 99 93 60 33] --> Fail
[33 34 90 39 29 50] --> Fail
[ 66  86  35  56  79 100] --> Fail
[66 21 46 34 38 57] --> Fail
[81 81  1 18 78 67] --> Fail
[30 77 64 13 36 97] --> Fail
